name: Environment Variables Usage

on:
  workflow_dispatch:

env:
  # Basic hardcoded environment variables
  LOCAL_USER: "Neha Lad"
  ENVIRONMENT: "DevOps Training"

jobs:
  show-env:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”¹ Print hardcoded env values
        run: |
          echo "ğŸ‘¤ Local User: $LOCAL_USER"
          echo "ğŸŒ Environment: $ENVIRONMENT"

      - name: ğŸ” Printing Values from GitHub Secrets & Variables
        env:
          USER_FROM_SECRET: ${{ secrets.USER_NAME }}
          PROJECT_FROM_VAR: ${{ vars.PROJECT_NAME }}
        run: |
          echo "ğŸ” Secret User: $USER_FROM_SECRET"
          echo "âš™ï¸ Project: $PROJECT_FROM_VAR"
